name: trips
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.18
  firebase_core: ^1.14.1
  firebase_messaging: ^11.2.13
  google_sign_in: ^5.3.1
  firebase_storage: ^10.2.16
  cloud_firestore: ^3.1.16
  flutter:
    sdk: flutter
  generic_bloc_provider: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/perfil.jpg
    - assets/img/river.jpeg
    - assets/img/beach.jpeg
    - assets/img/mountain.jpeg
    - assets/img/sunset.jpeg

  fonts:
    - family: JB
      fonts:
        - asset: fonts/JetBrainsMonoRegular.ttf
    - family: Lato
      fonts:
        - asset: fonts/Lato.ttf
